### ISSUE TITLE
Is the PROMINENCE_OIDC_URL env variable really needed?

### ISSUE THREAD

**Issue by alahiff** [prominence-eosc/cli#7]
it would be much simpler to just have a single URL...

**Comment by alahiff** [comment]
Closing, users no longer need to specify env variables.

**Comment by fcasson** [comment]
So after updating the client, I can delete this var from our setup?

**Comment by alahiff** [comment]
@fcasson Yes, that's correct. You don't actually need to define any PROMINENCE related env variables anymore when using the CLI.

**Comment by fcasson** [comment]
We have

```
$PROMINENCE_OIDC_CLIENT_ID
$PROMINENCE_OIDC_URL
$PROMINENCE_OIDC_CLIENT_SECRET
$PROMINENCE_URL
```

Presumably we still need to set $PROMINENCE_URL either in env or in args to the CLI ?

**Comment by alahiff** [comment]
`PROMINENCE_URL` is not needed as the appropriate value is set by default in the CLI if the env var doesn't exist. However, the JAMS Python scripts use it so you should actually keep it defined.

I had forgotten about `PROMINENCE_OIDC_CLIENT_ID` and `PROMINENCE_OIDC_CLIENT_SECRET`: you should keep these as they override the values that would normally be used (to provide longer-lived tokens I think).

So `PROMINENCE_OIDC_URL` is the only one you can remove, sorry.
